### ISSUE TITLE
Typo in es-theme-tronkyfran/tg16/theme.xml

### ISSUE THREAD

**Issue by roachman5000** [HerbFargus/es-theme-tronkyfran#1]
Hi,

Just went through a Retropie build using your theme and couldn't get the TurboGrafx 16 artwork to show up no matter what.  After digging around I looked into your .xml file in the TG16 folder and found a typo on line 8 where it says:

			<path>./art/tgc16_art_blur.jpg</path>

whereas it should say:

			<path>./art/tg16_art_blur.jpg</path>

After making that change I reloaded the theme and everything comes up as it should.

Thank you for your time!  I love the theme, btw.  It's my go-to from here on out.

**Comment by HerbFargus** [comment]
Thanks for the heads up, should be resolved via https://github.com/HerbFargus/es-theme-tronkyfran/commit/a89b9091acc8005d769099de566639d3d9c46849

Let me know if i missed anything else.

**Comment by roachman5000** [comment]
Hi, me again.  I found the same error in the tgcd folder (the jpg.jpg file name)

I just added Turbografx CD games, and that's how I came across it.

**Comment by roachman5000** [comment]
Similarly, I found this in the theme.xml as well

<path>./art/tg16_1.svg</path>

changed it to

<path>./art/tgcd.svg</path>

**Comment by HerbFargus** [comment]
Thanks, I'm out on holiday, will fix when I get back

**Comment by HerbFargus** [comment]
@roachman5000 they should be fixed now, thanks for testing
