### ISSUE TITLE
Include install instructions and some minor improvements

### ISSUE THREAD

**Issue by raelgc** [HerbFargus/es-theme-tronkyfran#15]
I know that for some this is trivial, but I got asked several times how themes can be installed.

I'm thinking to include:
- "manual" instructions (using `wget`, suitable for desktop)
- `git` instructions (suitable for retropie, so user can update just running a `git pull`)

Additionally I'm thinking to:
- move the credits to a Credits section (still in the `README` file)
- move the CHANGELOG to a `CHANGELOG.txt` file (to remove some pollution)
- and if you @HerbFargus allow, include myself in the Credits section too

**Comment by HerbFargus** [comment]
All points sound good to me. Community project so only fair that those that contribute receive attribution
