### ISSUE TITLE
add video support

### ISSUE THREAD

**Issue by HerbFargus** [HerbFargus/es-theme-tronkyfran#2]
I've been meaning to do this but lack the free time and motivation, but if someone gets to it before me I'd be happy to merge.

**Comment by HerbFargus** [comment]
I've added it kinda. if someone wants to tweak it to make it better feel free. I personally think metadata is stupid if you have video previews so I don't see it necessary.

**Comment by kneli** [comment]
I've cleaned up the video preview and created a pull request for it. Hope you can find the time to review and merge if you like it.

**Comment by HerbFargus** [comment]
Thanks, I'll review it when I get a free moment.

**Comment by HerbFargus** [comment]
this should be resolved as far as i am aware
