### ISSUE TITLE
Marquees placement

### ISSUE THREAD

**Issue by tcamargo** [HerbFargus/es-theme-tronkyfran#23]
Hi!

Just found your es-theme. Great work! 
I have marquees for all my games and tronkyfran is not displaying them properly. They are behind the header bar. What about removing the system name, moving the system logo to the right and leave the upper left of the screen to the marquee ("md_marquee")?

Thanks!

**Comment by raelgc** [comment]
Hi @tcamargo,

Can you, please, provide a screenshot?

**Comment by tcamargo** [comment]
hi @raelgc,
See the screenshot below:
![marquee-problem](https://user-images.githubusercontent.com/52097/44889340-da7fe500-acab-11e8-96ae-3ba57b70b2da.png)
Marquee is behind the gray area/header.

**Comment by tcamargo** [comment]
For your reference, this is what I get with the Carbon theme.
![marquee-ok](https://user-images.githubusercontent.com/52097/44912992-42611a80-ad02-11e8-9ae7-b9fa438f87f0.png)

**Comment by raelgc** [comment]
Nice, thanks for this gentle move including a screenshot of it working in another theme! Now it's clear how it should works! :+1: 

In fact, I'm working in updated theme for tronkyfran images (as the current one is just Simple or Dark with tronkyfran images). The top has similar arrangement as Carbon: console name at the left, control image at the right.

**Comment by tcamargo** [comment]
Just for clarification: I am talking about the clearart/marquee image (the Chrono Trigger title screen image in the screenshot) and not the joystick.

If you already have an updated theme, please, let me know. I can test it.

**Comment by Villemann** [comment]
I understand this theme is abandoned and this marquee problem wont be fixed?
