### ISSUE TITLE
Switching logos PCE to TG16

### ISSUE THREAD

**Issue by vinceroni** [HerbFargus/es-theme-tronkyfran#3]
First, great theme. The artwork is fantastic.

I'm doing the logo switching for Genesis and TG16, described here...
https://github.com/retropie/retropie-setup/wiki/Genesis-Megadrive

My code looks like:

```
megadrive_theme = "genesis"
megadrive_platform = "genesis"

pcengine_theme = "tg16"
pcengine_platform = "tg16"  // with and without this line
```

The MD to Genesis art swap works perfectly.
The TG16 logo loads, but no console art appears.

**Comment by HerbFargus** [comment]
I'll give you a hint why. 

its because I'm an idiot. 

should be fixed now.

**Comment by vinceroni** [comment]
Lol. Thank you for your service :)
