### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by raelgc** [HerbFargus/es-theme-tronkyfran#5]
Hi @HerbFargus and thanks for this AWESOME theme.

I like the ES simple themes too, the only difference is I prefer the simple dark.

So, I've create locally in my machine this variation and was thinking how you can keep this in you repo (if you want, of course). Maybe in a branch and later publish releases for both? (If yes, I can create the PR).

Side note: I've noticed that on a pi3 the full HD images are a bit heavy (ES suffers a very small hiccup during the platform transition effect). I've reduced the images to 1280x720 and they're still nice in a 1080p LED display, but now the transition effect is very smooth. Not sure if you want use this too.

**Comment by HerbFargus** [comment]
Dark theme is a cool idea.

I was also thinking it would be a good idea to have a slim/optimised version for the pi. What is your method for optimising the images?

**Comment by raelgc** [comment]
@HerbFargus, I resized them to 1280x720 with 90% quality (they were between 92% and 99% quality). I also fixed some console help text colors (they were almost black, for snes, megadrive and some others).

**Comment by raelgc** [comment]
I can submit a PR with those changes. If you want to add me as a contributor, I can keep all this stuff in a separate branch.

**Comment by kneli** [comment]
These improvements sound good. (Y) GJ.

On a side note, the custom collections (favorites, last played etc.) have yet to be added. Obviously artwork that would match the current style of the other systems would look best. @HerbFargus did you make this artwork yourself?

**Comment by HerbFargus** [comment]
@kneli I'm flattered but no that was tronkyfran who is the main genius behind it all. I just host assets for him. I believe he created a favourites wallpaper for custom collections on his thread on the RetroPie forum. I need to add it if I haven't already

**Comment by HerbFargus** [comment]
@raelgc I added you as a collaborator. Yes I think branches are a good idea: perhaps a tronkyfran-optimised, dark, dark-optimised. Idk whatever you deem sufficient

**Comment by kneli** [comment]
Okay, I added favorites with my own wallpaper on my retropie image which was done in two minutes. I think almost everyone is going to use the favorites option from now on so having it in the tronkyfran theme is a must I suppose :P But if you don't have the time I could look up the wallpaper and create a PR for it, just need a logo then ([I'm using this one myself](http://lesfavorites.nl/wp-content/uploads/2017/07/logo-e1498908886580.png))

**Comment by HerbFargus** [comment]
I'm on mobile so if you wouldn't mind.

Link here:

https://retropie.org.uk/forum/post/94557

**Comment by kneli** [comment]
I don't have time atm as well, I'll fix it later this weekend.

**Comment by raelgc** [comment]
Fixed in commit https://github.com/HerbFargus/es-theme-tronkyfran/commit/b6036d2f6555bdf80df6717441388a5147f4b0b8
