### ISSUE TITLE
Suggestion: update README

### ISSUE THREAD

**Issue by raelgc** [HerbFargus/es-theme-tronkyfran#8]
@HerbFargus Can I improve the readme file? These are my suggestions:

1. Use markdown for it (nice to read as text file, but will render as HTML in GitHub)
2. Point to the dark and optimized variations branches.
3. Move `license.txt` to a separate file but keep it a `License` section linking to it (it's a good practice keep License mentioned in the Readme and as a separate file).

If you agree with above points, I'll submit this as a PR so you can evaluate it.

**Comment by HerbFargus** [comment]
I agree having the license separate but I think we should still have a note on the main readme clearly noting it is for non-commercial use. not that made any difference to retrodouchebagma...

It's pretty much a copy pasta of simple and as such inherits the same licence
